In [3]:
import torch
from typing import List, Dict, Tuple, Any
from kobert_transformers import get_tokenizer, get_kobert_model
from gluonnlp.data import SentencepieceTokenizer

In [5]:
tokenizer = get_tokenizer()
model = get_kobert_model()
tok = tokenizer('뽀로로는 남극에 사는 펭귄이 아니다.', padding=True, truncation=True) # Has Input_ids, token_type_ids, attention_mask
res = tokenizer.convert_ids_to_tokens(tok['input_ids'])
print(tokenizer.convert_tokens_to_ids(res))
print(type(tok['attention_mask']))

[2, 517, 6478, 6079, 6079, 5760, 1409, 5543, 6896, 2582, 517, 0, 5531, 7096, 3100, 54, 3]
<class 'list'>


In [37]:
import numpy as np
x = np.array([1, 2, 3, 4, 5])
t = np.random.choice(np.array([2, 3, 4]), size = 2)
np.delete(x, t)

array([1, 2, 3])

In [75]:
import torch
import torch.nn as nn
from kobert_transformers import get_kobert_model, get_distilkobert_model
from TorchCRF import CRF
model = get_kobert_model()
model.eval()
# input_ids = torch.LongTensor([[31, 51, 99], [15, 5, 0]])
input_ids = torch.LongTensor([[31, 51, 99], [15, 5, 0]])
attention_mask = torch.LongTensor([[1, 1, 1], [1, 1, 0]])
token_type_ids = torch.LongTensor([[0, 0, 1], [0, 1, 0]])
ans = torch.LongTensor([[0, 1, 2], [2, 3, 4]])
xx = model(input_ids, attention_mask, token_type_ids)[0]
md = nn.Linear(768, 5)
# No mask
xxx = md(xx)
print(type(xxx))
crf = CRF(num_labels=5)
i = [torch.LongTensor([1, 2]), torch.LongTensor([2, 3, 4])]
j = [torch.LongTensor([2, 2]), torch.LongTensor([1, 3, 5])]
# print(torch.sum([torch.LongTensor(i==j) for (i1, j1) in zip(i, j)]))
mask = torch.BoolTensor([[1, 0, 1], [1, 1, 1]])
print(mask)
print(type(crf.viterbi_decode(xxx, mask)), crf.viterbi_decode(xxx, mask))

<class 'torch.Tensor'>


RuntimeError: stack expects each tensor to be equal size, but got [2] at entry 0 and [3] at entry 1

In [38]:
print(type(input))

In [25]:
from torch.nn.utils.rnn import pad_sequence
model.eval()
res = tokenizer(['배를 먹다.', '뽀로로는 남극에 사는 펭귄이 아니다.'], padding=True, truncation=True, return_tensors='pt')
print(res['input_ids'])
texts = []
for idx, i in enumerate(res['input_ids']) :
    texts.append(i[:idx+4])
# texts = [res[0]['input_ids'][:3], res[1]['input_ids'][:5]]
print(texts)
texts = pad_sequence(texts, batch_first=True, padding_value= -1)
print(texts)
seq, pooled_output  = model(**res)
print(seq)
print(model(**res)[seq])

tensor([[   2, 2287, 6116, 2010, 5782,   54,    3,    1,    1,    1,    1,    1,
            1,    1,    1,    1,    1],
        [   2,  517, 6478, 6079, 6079, 5760, 1409, 5543, 6896, 2582,  517,    0,
         5531, 7096, 3100,   54,    3]])
[tensor([   2, 2287, 6116, 2010]), tensor([   2,  517, 6478, 6079, 6079])]
tensor([[   2, 2287, 6116, 2010,   -1],
        [   2,  517, 6478, 6079, 6079]])
last_hidden_state
tensor([[[-0.0049,  0.1500,  0.0795,  ..., -0.2515,  0.3697,  0.2850],
         [ 0.0881,  0.2531,  0.4122,  ..., -0.5684, -0.2381,  0.2486],
         [ 0.1131, -0.0638,  0.2878,  ...,  0.0902, -0.5898,  0.2046],
         ...,
         [-0.0308, -0.0373,  0.0136,  ..., -0.1681,  0.0115, -0.0494],
         [-0.0308, -0.0373,  0.0136,  ..., -0.1681,  0.0115, -0.0494],
         [-0.0308, -0.0373,  0.0136,  ..., -0.1681,  0.0115, -0.0494]],

        [[ 0.1627, -0.0937,  0.0815,  ...,  0.2031,  0.2887, -0.0510],
         [ 0.0094, -0.1836,  0.2938,  ..., -0.2896, -0.1239, -0.4415],

In [43]:
aa = [{1: 2, 2:4}, {1: 4, 2: 7}]
print({key: [i[key] for i in aa] for key in aa[0]})

{1: [2, 4], 2: [4, 7]}


In [4]:
label_list = ['PS', 'FD', 'TR', 'AF', 'OG', 'LC', 'CV', 'DT', 'TI', 'TI', 'QT', 'EV', 'AM', 'PT', 'MT', "TM"] 
label_fin = ['O']
label_fin += ['B-' + i for i in label_list]
label_fin += ['I-' + i for i in label_list]
label_to_idx = {label: idx for idx, label in enumerate(label_fin)}
idx_to_label = {idx: label for idx, label in enumerate(label_fin)}
print(label_to_idx, idx_to_label)

{'O': 0, 'B-PS': 1, 'B-FD': 2, 'B-TR': 3, 'B-AF': 4, 'B-OG': 5, 'B-LC': 6, 'B-CV': 7, 'B-DT': 8, 'B-TI': 10, 'B-QT': 11, 'B-EV': 12, 'B-AM': 13, 'B-PT': 14, 'B-MT': 15, 'B-TM': 16, 'I-PS': 17, 'I-FD': 18, 'I-TR': 19, 'I-AF': 20, 'I-OG': 21, 'I-LC': 22, 'I-CV': 23, 'I-DT': 24, 'I-TI': 26, 'I-QT': 27, 'I-EV': 28, 'I-AM': 29, 'I-PT': 30, 'I-MT': 31, 'I-TM': 32} {0: 'O', 1: 'B-PS', 2: 'B-FD', 3: 'B-TR', 4: 'B-AF', 5: 'B-OG', 6: 'B-LC', 7: 'B-CV', 8: 'B-DT', 9: 'B-TI', 10: 'B-TI', 11: 'B-QT', 12: 'B-EV', 13: 'B-AM', 14: 'B-PT', 15: 'B-MT', 16: 'B-TM', 17: 'I-PS', 18: 'I-FD', 19: 'I-TR', 20: 'I-AF', 21: 'I-OG', 22: 'I-LC', 23: 'I-CV', 24: 'I-DT', 25: 'I-TI', 26: 'I-TI', 27: 'I-QT', 28: 'I-EV', 29: 'I-AM', 30: 'I-PT', 31: 'I-MT', 32: 'I-TM'}


# Preprocess Part

In [5]:
'''
We will return the label of given words, using the ne_lists
We use BIO-tagging
'''
def tagging(words: List[str], ne_lists: List[Dict[str, Any]]) -> List[str] :
    results = [i if i in ['[CLS]', '[SEP]', '[PAD]'] else 'O' for i in words] # If token is not Special, initialize 'O' tag
    ps_words = [i.replace('##', '').replace('▁','') for i in words]
    ne_cnt = len(ne_lists)
    ne_idx = -1
    ne_label = 0

    for idx, word in enumerate(ps_words) :
        if results[idx] != 'O' or word == '' or word == '[UNK]':
            continue
        if word == '[UNK]' :
            continue
        # Now condition check
        if ne_idx >= 0 : 
            nw_word = ne_lists[ne_idx]['form'][ne_label:]
        else :
            nw_word = ''

        # I-tag condition
        if (len(nw_word) > 0) & (nw_word.startswith(word)) & (results[idx-1][0] == 'B' or results[idx-1][0] == 'I') :
            results[idx] = 'I-' + ne_lists[ne_idx]['label'][:2]
            ne_label += len(word)
        else : # B-tag condition
            back_idx = ne_idx
            back_label = ne_label
            while ne_idx + 1 < ne_cnt :
                ne_idx += 1
                ne_label = 0
                nw_word = ne_lists[ne_idx]['form']
                if (len(nw_word) > 0) & (nw_word.startswith(word)) :
                    results[idx] = 'B-' + ne_lists[ne_idx]['label'][:2]
                    ne_label += len(word)
                    break
            if ne_idx + 1 == ne_cnt and ne_label == 0:
                ne_idx = back_idx
                ne_label = back_label

    return results


In [6]:
sentence = "태안군의회, 2019년‘군민중심’의정성과 빛났다!"
ne = [
        {
            "id": 1,
            "form": "태안군의회",
            "label": "OGG_POLITICS",
            "begin": 0,
            "end": 5
        },
        {
            "id": 2,
            "form": "2019년",
            "label": "DT_YEAR",
            "begin": 7,
            "end": 12
        }
]

tokenizer = get_tokenizer()
tok = tokenizer(sentence, padding=True, truncation=True) # Has Input_ids, token_type_ids, attention_mask
tokens_word = tokenizer.convert_ids_to_tokens(tok['input_ids'])
print(tokens_word, tagging(tokens_word, ne), sep='\n')

['[CLS]', '▁태', '안', '군의', '회', ',', '▁20', '19', '년', '‘', '군', '민', '중심', '’', '의', '정', '성과', '▁빛', '났다', '!', '[SEP]']
['[CLS]', 'B-OG', 'I-OG', 'I-OG', 'I-OG', 'O', 'B-DT', 'I-DT', 'I-DT', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', '[SEP]']


# Json loads & dataframe preprocess

In [7]:
import json
import pandas as pd

def load_files(path='./dataset/NLNE2202211219.json') :
    with open(path, "r") as f :
        bef_data = json.load(f)

    bef_data = bef_data['document']

    df_tot = pd.DataFrame(columns=['form', 'NE'])

    for r in bef_data :
        df_tot = df_tot.append(pd.DataFrame.from_records(r['sentence'], columns=['form', 'NE']))

    df_tot.dropna(how='any', inplace=True)

    return df_tot

In [8]:
# def convert_df(data: List[Any]) -> pd.DataFrame:
#     return pd.DataFrame.from_records(data['sentence'], columns=['form'])
# ex = bef_data[0]
# ex = ex['sentence']
# print(type(ex), ex[1], sep='\n')
# df = pd.DataFrame.from_records(ex, columns=['form', 'NE'])
# df

In [9]:
devices = torch.device('cuda:0' if torch.cuda.is_available() else 'cpu')
# Define DataLoader, with tokenizer
# Have to define collect_fn, to gather attention mask and another information
# tok = tokenizer('뽀로로는 남극에 사는 펭귄이 아니다.', padding=True, truncation=True) # Has Input_ids, token_type_ids, attention_mask
# tokenizer.convert_ids_to_tokens(tok['input_ids'])
df = load_files()
texts = df['form'].to_list()
ne = df['NE'].to_list()

# DataLoader

In [10]:
import os
import torch
from torch.utils.data import Dataset

class CustomDataset(Dataset) :
    def __init__(self, texts, labels, tokenizer, max_len = 256) -> None:
        self.tokenizer = tokenizer 
        self.texts = texts
        self.labels = labels
        self.max_len = max_len

    def __len__(self) :
        return len(self.texts)
    
    def __getitem__(self, index) -> Any:
        # tokenizer
        input = self.texts[index]
        sentence = self.tokenizer(input, padding = 'max_length', truncation = True, max_length = self.max_len) # Input_ids, token_type_ids, attention_mask
        tags = tagging(self.tokenizer.convert_ids_to_tokens(sentence['input_ids']), self.labels[index])
        convert_tags = [-100 if i in ['[CLS]', '[SEP]', '[PAD]'] else label_to_idx[i] for i in tags]
        return {
            'sentence' : input, # str
            'input_ids' : torch.tensor(sentence['input_ids'], dtype=torch.long).to(devices),
            'token_type_id' : torch.tensor(sentence['token_type_ids'], dtype=torch.long).to(devices),
            'attention_mask' : torch.tensor(sentence['attention_mask'], dtype=torch.long).to(devices),
            'labels' : torch.tensor(convert_tags, dtype=torch.long).to(devices)
        } # Collect_fn?

In [11]:
from torch.utils.data import DataLoader
from sklearn.model_selection import train_test_split

train_texts, test_texts, train_ne, test_ne = train_test_split(texts, ne, test_size=0.2, random_state=42)
test_dataset = CustomDataset(test_texts, test_ne, tokenizer)
test_loader = DataLoader(test_dataset, batch_size = 32, shuffle=True)

In [2]:
import torch
a = torch.tensor([[1, 2], [3], [4, 5, 6]])

/home/sung/anaconda3/envs/cose362/lib/python3.7/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


ValueError: expected sequence of length 2 at dim 1 (got 1)

In [14]:
cnt = 0
for batch in test_loader :
    if cnt > 1 :
        break
    cnt += 1
    print(len(batch), len(batch['sentence']), sep='\n')

5
32
5
32
